#!/usr/bin/env sh
set -x
set -e
if [ "$1" = "run" -o -z "$1" ]; then
  sudo /var/cfengine/bin/cf-agent -KIf update.cf
  sudo /var/cfengine/bin/cf-agent -KI
  exit 0
fi
if [ "$1" = "uninstall" ]; then
  echo "uninstalling CFEngine..."
  systemctl stop cfengine3
  /etc/init.d/cfengine3 stop
  apt remove -qy cfengine-nova-hub
  apt remove -qy cfengine-nova
  # TODO dnf, yum, zypper, apk, etc :)
  rm -rf /var/cfengine
  rm -rf /opt/cfengine
  rm -rf /var/log/CFE*
  rm -f /var/log/postgresql
  pkill -9 httpd
  pkill -9 cf-*
  echo "done uninstalling CFEngine"
  exit 0
fi

echo "usage: $0 <subcommand>"
echo "  subcommands: uninstall"
# commands todo
bootstrap
hosts report
inventory report
health info status
license status
dashboard
compliance scores
policy analyzer
recent not kept promises
