#!/usr/bin/env sh
if [ "$1" = "uninstall" ]; then
  echo "uninstalling CFEngine..."
  systemctl stop cfengine3
  /etc/init.d/cfengine3 stop
  apt remove -qy cfengine-nova-hub
  apt remove -qy cfengine-nova
  # TODO dnf, yum, zypper, apk, etc :)
  rm -rf /var/cfengine
  rm -rf /opt/cfengine
  rm -rf /var/log/CFE*
  rm -f /var/log/postgresql
  pkill -9 httpd
  pkill -9 cf-*
  echo "done uninstalling CFEngine"
  exit 0
fi

echo "usage: $0 <subcommand>"
echo "  subcommands: uninstall"
