FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y curl libexpat1 net-tools dnsutils && \
    curl -O https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.21.0/hub/ubuntu_22_x86_64/cfengine-nova-hub_3.21.0-1.ubuntu22_amd64.deb && \
    dpkg -i cfengine-nova-hub_3.21.0-1.ubuntu22_amd64.deb && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" && \
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm -f kubectl kubectl.sha256 cfengine-nova-hub_3.21.0-1.ubuntu22_amd64.deb # cfengine-masterfiles-3.21.0-1.pkg.tar.gz masterfiles
COPY ./entrypoint-hub.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
