apiVersion: v1
kind: Namespace
metadata:
  name: cfengine
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  namespace: cfengine
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-pods-list
  namespace: cfengine
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  namespace: cfengine
subjects:
- kind: ServiceAccount
  name: default
  namespace: cfengine
roleRef:
  kind: Role
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list-global
subjects:
- kind: ServiceAccount
  name: default
  namespace: cfengine
roleRef:
  kind: ClusterRole
  name: cluster-pods-list
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cfengine-hub
  namespace: cfengine
spec:
  selector:
    matchLabels:
      app: cfengine-hub
  serviceName: "cfengine-hub"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: cfengine-hub
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
      containers:
      - name: hub
        image: localhost:5000/cfengine-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: hub-http
        - containerPort: 443
          name: hub-https
# TODO: volumeMounts for /var/cfengine/state/pg for data persistency

---
apiVersion: v1
kind: Service
metadata:
  name: cfengine-hub
  namespace: cfengine
spec:
  ports:
  - name: hub-http
    port: 80
  - name: hub-https
    port: 443
  selector:
    app: cfengine-hub
