########################################################################
# Acceptance test framework.
#
# See README for details about writing test cases.
########################################################################
bundle common D
{
  vars:
    any::

      "owndir" string => "$(this.promise_dirname)";

      "inputs"
        slist => {
                   "$(D.owndir)$(const.dirsep)dcs.cf.sub",
                   "$(D.owndir)$(const.dirsep)..$(const.dirsep)..$(const.dirsep)lib$(const.dirsep)stdlib.cf"
                 };


}

body file control
{
      # plucked.cf.sub comes from the stdlib with `make pluck`
      inputs => { @(D.inputs) };
}
