#!/usr/bin/env bash
set -ex
COMPUTED_ROOT="$(readlink -e "$(dirname "$0")/../../../../")"
# NTECH_ROOT should be the same, but if available use it so user can do their own thing.
NTECH_ROOT=${NTECH_ROOT:-$COMPUTED_ROOT}
PWD="${NTECH_ROOT}/core/contrib/docker"

name=cfengine-chroot-agent
docker build -t "$name" -f "${PWD}/Dockerfile-cfengine-chroot-agent" "${PWD}"
docker run -d --env CFENGINE_HUB_IP --privileged \
  -v "/:/rootfs" \
  -v "/proc:/rootproc" \
  -v "/sys:/rootsys" \
  -v "/dev:/rootdev" \
  -v "/run:/rootrun" \
  --name "$name" \
  "$name"
