name: Valgrind Check

on:
  workflow_call

jobs:
  valgrind_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Together Action
      uses: actions/checkout@v3
      with:
        repository: cfengine/together-javascript-action
        ref: main
        ssh-key: ${{ secrets.GH_ACTIONS_SSH_DEPLOY_KEY_TOGETHER_REPO }}
        ssh-known-hosts: github.com

    - name: Action step
      uses: ./
      id: together
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Core
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: core

    - name: Checkout Masterfiles
      uses: actions/checkout@v3
      with:
        repository: cfengine/masterfiles
        submodules: recursive
        path: masterfiles
        ref: ${{steps.together.outputs.masterfiles || github.base_ref}}

    - name: Run The Test
      working-directory: ./core/tests/valgrind-check
      run: sudo bash run.sh
